name: hls_cog2_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.2
  - numpy
  - gdal
  - rasterio
  - rioxarray
  - shapely
  - geopandas
  - geoviews
  - holoviews
  - xarray
  - matplotlib
  - cartopy
  - scikit-image
  - scikit-learn
  - hvplot
  - pyepsg
  - jupyterlab >= 3.0
  - jupyter-server-proxy
  - jupyter-panel-proxy
  - jupyter_bokeh
  - pyviz_comms
  - panel
  - dask-labextension
  - param
  - statsmodels
  - cvxopt
  - nbgitpuller>=0.9.0
  - pip
  - pip:
        - pysptools
        - sat-search
        - stackstac
