channels:
  - conda-forge
  - defaults
dependencies:
  - gdal
  - rasterio
  - shapely
  - geopandas
  - geoviews
  - holoviews
  - xarray
  - matplotlib
  - cartopy
  - scikit-image
  - hvplot
  - pyepsg
  - jupyterlab
  - jupyter-server-proxy
  - jupyter-panel-proxy
  - panel
  - dask-labextension
  - param
  - hvplot
  - statsmodels
  - cvxopt
  - pip:
        - pysptools
