#!/bin/bash
jupyter labextension install @jupyterlab/server-proxy \
                             dask-labextension
jupyter labextension install jupyterlab_bokeh
jupyter labextension install @pyviz/jupyterlab_pyviz
jupyter labextension install @jupyterlab/server-proxy
jupyter labextension install @jupyterlab/panel-proxy

#EOF
